heat_template_version: 2013-05-23


description: Blueprint CoreOS Zimbra


parameters:
  keypair_name:
    description: Keypair to inject in instance
    label: SSH Keypair
    type: string

  flavor_name:
    default: n1.cw.standard-1
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - n1.cw.standard-1
          - n1.cw.standard-2
          - n1.cw.standard-4
          - n1.cw.standard-8
          - n1.cw.standard-12
          - n1.cw.standard-16

  Domain_Name:
    description: Domain name
    type: string

  DNS_server:
    description: DNS Server IP
    type: string  

  Zimbra_Password:
    description: Zimbra Admin Pass
    type: string
    hidden: true

resources:
  network:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      dns_nameservers:
        - 185.23.94.244
        - 185.23.94.245
      cidr: 10.0.1.0/24
      allocation_pools:
        - { start: 10.0.1.100, end: 10.0.1.199 }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: ingress, protocol: TCP, port_range_min: 443, port_range_max: 443 }
        - { direction: ingress, protocol: TCP, port_range_min: 7071, port_range_max: 7071 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }
  
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  ports:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: network }
      fixed_ips:
        - ip_address: 10.0.1.254
          subnet_id: { get_resource: subnet }
      security_groups:
        - { get_resource: security_group }

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: CoreOS Stable 1010.6
      flavor: { get_param: flavor_name }
      user_data_format: RAW
      networks:
        - port: { get_resource: ports }
      user_data:
        str_replace:
          params:
            $private_ipv4: { get_attr: [ ports, fixed_ips, 0, ip_address ] }
            $public_ipv4: { get_attr: [floating_ip, floating_ip_address] }
            $Zimbra_Password: { get_param: Zimbra_Password }
            $Domain_Name: { get_param: Domain_Name }
            $DNS: { get_param: DNS_server }
          template: |
            #cloud-config
            write_files:
              - path: /home/core/format.sh
                permissions: 0755
                owner: "root:root"
                content: |
                  #!/bin/bash
                  sudo mkdir -p /zimbra/
              - path: /home/core/zimbra.env
                permissions: 0775
                owner: "core:core"
                content: |
                    PASSWORD=$Zimbra_Password
            coreos:
              etcd2:
                name: "%H"
                advertise-client-urls: http://$private_ipv4:2379
                initial-advertise-peer-urls: http://$private_ipv4:2380
                initial-cluster: "%H=http://$private_ipv4:2380"
                listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
                listen-peer-urls: http://$private_ipv4:2380
              units:
                - name: etcd2.service
                  command: start
                - name: fleet.service
                  command: start
                - name: docker-tcp.socket
                  command: start
                  enable: true
                  content: |
                    [Unit]
                    Description=Docker Socket for the API
                    [Socket]
                    ListenStream=2375
                    BindIPv6Only=both
                    Service=docker.service
                    [Install]
                    WantedBy=sockets.target
                - name: format.service
                  command: start
                  content: |
                    [Unit]
                    Description=Create Zimbra Folder
                    [Service]
                    Type=oneshot
                    RemainAfterExit=yes
                    ExecStart=/home/core/format.sh                  
                - name: zimbra.service
                  command: start
                  content: |
                    [Unit]
                    Description=Zimbra install 
                    After=docker.service
                    Requires=docker.service
                    [Service]
                    TimeoutStartSec=0
                    ExecStartPre=-/usr/bin/docker kill zimbra
                    ExecStartPre=-/usr/bin/docker rm zimbra
                    ExecStartPre=/usr/bin/docker pull jorgedlcruz/zimbra
                    ExecStart=/usr/bin/docker run \
                             --volume /zimbra/:/opt/zimbra \
                             --publish=25:25 \
                             --publish=80:80 \
                             --publish=110:110 \
                             --publish=143:143 \
                             --publish=443:443 \
                             --publish=456:456 \
                             --publish=587:587 \
                             --publish=993:993 \
                             --publish=995:995 \
                             --publish=7071:7071 \
                             --publish=8080:8080 \
                             --publish=8443:8443 \
                             --publish=9071:9071 \
                             --env-file /home/core/zimbra.env \
                             --dns=$DNS \
                             --dns=8.8.8.8 \
                             --hostname=zimbra86-docker.$Domain_Name \
                             --name=zimbra jorgedlcruz/zimbra

                    [Install]
                    WantedBy=multi-user.target

  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }

outputs:
  floating_ip_url:
    description: owncloud URL
    value:
      str_replace:
        template: http://$floating_ip
        params:
          $floating_ip: { get_attr: [floating_ip, floating_ip_address] }