---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: servers
  become: yes

  vars:
    package: zabbix
    service_web: "{{ lookup('env', 'SERVICE_WEB_HOST') }}:{{ lookup('env', 'SERVICE_WEB_PORT') }}"
    service: "{{ lookup('env', 'SERVICE_ACTIVE_HOST') }}:{{ lookup('env', 'SERVICE_ACTIVE_PORT') }}"
    service_username: "Admin"
    service_password: "zabbix"

  tasks:

    - apt: update_cache=true upgrade=full
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Add repository for CentOS 7
      yum:
        name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
        state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "7"

    - name: Add repository for CentOS 6
      yum:
        name=http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm
        state=present
      when: ansible_distribution == "CentOS" and ansible_distribution_version.split(".")[0] == "6"

    - name: install packages
      package: name={{ item }} state=present
      with_items:
        - zabbix-agent

    - name: set ServerActive IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*ServerActive=.*"
        line="ServerActive={{ service }}"
      notify: restart zabbix

    - name: set Server IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*Server=.*"
        line="Server={{ toolbox_address }}"
      notify: restart zabbix

    - name: set StartAgent to 0
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*StartAgents=.*"
        line="StartAgents=0"
      notify: restart zabbix

    - name: set Source IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*SourceIP=.*"
        line="SourceIP={{ server_ip }}"
      notify: restart zabbix

    - name: zabbix slave hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname={{ ansible_hostname }}"
      notify: restart zabbix

    - name: set selinux permissions
      selinux: policy=zabbix_agent_t state=permissive
      when: ansible_distribution == "CentOS"

    - name: register zabbix agent
      local_action:
          module: zabbix_host
          server_url: "http://{{ service_web }}"
          login_user: "{{ service_username }}"
          login_password: "{{ service_password }}"
          host_name: "{{ ansible_hostname }}"
          link_templates:
            - Template OS Linux
          host_groups:
            - Linux servers
          status: enabled
          state: present
          interfaces:
            - type: 1
              main: 1
              useip: 1
              ip: "{{ server_ip }}"
              dns: "{{ ansible_hostname }}"
              port: 10050

  handlers:
    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes





